# =========================
# Minimal Mistakes settings
# =========================
minimal_mistakes_skin: "air"   # "air","aqua","contrast","dark","dirt","neon","mint","plum","sunrise"
remote_theme: "mmistakes/minimal-mistakes@4.16.6"
# theme: jekyll-theme-time-machine   # ← REMOVE/COMMENT (conflicts with Minimal Mistakes)

# =================
# Site information
# =================
locale        : "en-US"
title         : "Home"
title_separator: "-"
name          : "Amrita Neogi"
description   : "An amazing website."
subtitle      :
url           :        # e.g. https://amritaneogi.github.io
baseurl       :        # e.g. /portfolio
repository    :
teaser        :
logo          :
masthead_title:
words_per_minute: 200

# ------------
# Comments
# ------------
comments:
  provider:        # false (default), "disqus", "utterances", "giscus", etc.
  disqus:
    shortname:
  discourse:
    server:
  facebook:
    appid:
    num_posts:
    colorscheme:
  utterances:
    theme: "github-dark"
    issue_term:
  giscus:
    repo_id:
    category_name:
    category_id:
    discussion_term:
    reactions_enabled:
    theme:
  staticman:
    branch:
    endpoint:

reCaptcha:
  siteKey:
  secret:

atom_feed:
  path:
  hide:

# Search
search              :
search_full_content :
search_provider     :  # lunr (default), algolia, google
lunr:
  search_within_pages:
algolia:
  application_id:
  index_name:
  search_only_api_key:
  powered_by:

# SEO
google_site_verification:
bing_site_verification:
naver_site_verification:
yandex_site_verification:
baidu_site_verification:

# Social
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:
social:
  type:
  name:
  links:

# Analytics
analytics:
  provider: false
  google:
    tracking_id:
    anonymize_ip:

# ===========
# Site Author
# ===========
author:
  name     : "Amrita Neogi"
  avatar   : "/assets/images/Amrita_avatar.png"
  location : "Austin, TX"
  email    : "neogiamrita111@gmail.com"
  links:
    - label: "amritaneogi@arizona.edu"
      icon : "fas fa-fw fa-envelope-square"
    - label: "Website"
      icon : "fas fa-fw fa-link"
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/AmritaNeogi"
    - label: "LinkedIn"
      url  : "https://www.linkedin.com/in/amritaneogi/"
    - label: "Instagram"
      icon : "fab fa-fw fa-instagram"

# ==========
# Site Footer
# ==========
footer:
  links:
    - label: "Facebook"
      icon : "fab fa-fw fa-facebook-square"
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
    - label: "GitLab"
      icon : "fab fa-fw fa-gitlab"
    - label: "Bitbucket"
      icon : "fab fa-fw fa-bitbucket"
    - label: "Instagram"
      icon : "fab fa-fw fa-instagram"

# ===============
# Reading / Build
# ===============
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn

encoding     : "utf-8"
markdown_ext : "markdown,mkdown,mkdn,mkd,md"

# ==========
# Conversion
# ==========
markdown    : kramdown
highlighter : rouge
lsi         : false
excerpt_separator: "\n\n"
incremental : false

# ==================
# Markdown Processing
# ==================
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# =========
# Sass/SCSS
# =========
sass:
  sass_dir: _sass
  style   : compressed

# ========
# Output
# ========
permalink    : /:categories/:title/
paginate     : 5
paginate_path: /page:num/
timezone     :

# =======
# Plugins
# =======
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# =======
# Archives
# =======
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# ===============
# HTML Compression
# ===============
compress_html:
  clippings: all
  ignore:
    envs: development

# =========
# Defaults
# =========
defaults:
  # Posts (keep your existing behavior)
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments:
      share: true
      related: true

  # Pages (SITE-WIDE): wide layout, NO sidebar by default
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar: false
